# Generated by Django 5.1.1 on 2024-11-12 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tu_events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('email', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.IntegerField(unique=True)),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='announcement',
            name='place',
            field=models.CharField(default='TU', max_length=200),
        ),
        migrations.AddField(
            model_name='found',
            name='description',
            field=models.TextField(default='description'),
        ),
        migrations.AddField(
            model_name='lost',
            name='description',
            field=models.TextField(default='description'),
        ),
    ]
