# Generated by Django 5.1.1 on 2024-11-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tu_events', '0007_alter_announcement_date_alter_announcement_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='lost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
