# Generated by Django 5.1.1 on 2024-11-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tu_events', '0008_club_image_alter_announcement_image_alter_lost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='categories',
            field=models.CharField(choices=[('entertainment', 'Entertainment'), ('sports', 'Sports'), ('cultural', 'Cultural'), ('religions', 'Religions'), ('education', 'Education')], max_length=100),
        ),
    ]
