# Generated by Django 5.1.1 on 2024-11-12 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tu_events', '0010_alter_announcement_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='end_date',
            field=models.DateTimeField(blank=True, help_text='กรอกวันที่สิ้นสุดกิจกรรม', null=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='กรอกวันที่เริ่มกิจกรรม', null=True),
        ),
    ]
