# Generated by Django 5.1.1 on 2024-11-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tu_events', '0011_alter_announcement_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='end_date',
            field=models.DateTimeField(help_text='กรอกวันที่สิ้นสุดกิจกรรม'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='start_date',
            field=models.DateTimeField(help_text='กรอกวันที่เริ่มกิจกรรม'),
        ),
    ]
