# Generated by Django 5.1.1 on 2024-11-16 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tu_events', '0012_student_is_active_alter_announcement_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
