# Generated by Django 5.1.1 on 2024-11-21 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tu_events', '0013_remove_student_is_active_alter_student_student_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='categories',
            field=models.CharField(choices=[('entertainment', 'Entertainment'), ('sports', 'Sports'), ('cultural', 'Cultural'), ('religions', 'Religions'), ('education', 'Education'), ('clubs', 'Clubs')], max_length=100),
        ),
    ]
