# Generated by Django 5.1.1 on 2024-11-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tu_events', '0014_alter_announcement_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='origin',
            field=models.CharField(choices=[('tu', 'Thammasat University (มหาวิทยาลัยธรรมศาสตร์)'), ('law', 'Faculty of Law (คณะนิติศาสตร์)'), ('business', 'Thammasat Business School (คณะพาณิชยศาสตร์และการบัญชี)'), ('political_science', 'Faculty of Political Science (คณะรัฐศาสตร์)'), ('economics', 'Faculty of Economics (คณะเศรษฐศาสตร์)'), ('social_administration', 'Faculty of Social Administration (คณะสังคมสงเคราะห์ศาสตร์)'), ('sociology_anthropology', 'Faculty of Sociology and Anthropology (คณะสังคมวิทยาและมานุษยวิทยา)'), ('liberal_arts', 'Faculty of Liberal Arts (คณะศิลปศาสตร์)'), ('journalism_mass_comm', 'Faculty of Journalism and Mass Communication (คณะวารสารศาสตร์และสื่อสารมวลชน)'), ('science_technology', 'Faculty of Science and Technology (คณะวิทยาศาสตร์และเทคโนโลยี)'), ('engineering', 'Faculty of Engineering (คณะวิศวกรรมศาสตร์)'), ('architecture_planning', 'Faculty of Architecture and Planning (คณะสถาปัตยกรรมศาสตร์และการผังเมือง)'), ('medicine', 'Faculty of Medicine (คณะแพทยศาสตร์)'), ('allied_health', 'Faculty of Allied Health Sciences (คณะสหเวชศาสตร์)'), ('dentistry', 'Faculty of Dentistry (คณะทันตแพทยศาสตร์)'), ('nursing', 'Faculty of Nursing (คณะพยาบาลศาสตร์)'), ('public_health', 'Faculty of Public Health (คณะสาธารณสุขศาสตร์)')], max_length=100),
        ),
    ]
