# Generated by Django 5.1.3 on 2024-11-23 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tu_events', '0016_found_date_found_time_lost_date_lost_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='found',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_tu_events.student'),
        ),
        migrations.AddField(
            model_name='lost',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_tu_events.student'),
        ),
    ]
