# Generated by Django 5.1.3 on 2024-11-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tu_events', '0017_found_student_lost_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(default='images/profile_image.jpg', upload_to='images/'),
        ),
    ]
