# Generated by Django 5.1.3 on 2024-11-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tu_events', '0018_alter_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='found',
            name='student',
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
