# Generated by Django 5.1.3 on 2024-11-23 05:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tu_events', '0019_remove_found_student_alter_student_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='found',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web_tu_events.student'),
        ),
    ]
