# Generated by Django 5.1.1 on 2024-11-30 02:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tu_events', '0021_interest'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='web_tu_events.club'),
        ),
    ]
