# Generated by Django 5.1.1 on 2024-11-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_tu_events', '0023_announcement_club'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='categories',
            field=models.CharField(choices=[('entertainment', 'Entertainment'), ('sports', 'Sports'), ('cultural', 'Cultural'), ('religions', 'Religions'), ('education', 'Education'), ('clubs', 'Clubs'), ('alerts', 'Alerts')], max_length=100),
        ),
    ]
